name: site
description: Testainers site

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  flutter_localizations:
  #    sdk: flutter

  # https://pub.dev/packages/google_fonts
  google_fonts: 6.2.1

  # https://pub.dev/packages/url_launcher
  url_launcher: 6.2.6

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
