name: site
description: Testainers site

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  flutter_localizations:
  #    sdk: flutter

  # https://pub.dev/packages/google_fonts
  google_fonts: ^5.1.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.12

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
